---
- name: playbook mltiple packages
  hosts: all
  become: true
  tasks:
  - name: install packages
    yum:
      name: ['git', 'make', 'gcc', 'wget', 'mysql', 'tree', 'which', 'docker']
      state: installed
...
